map_type: costmap

transform_tolerance: 0.5 # 0.0

#robot_radius: 0.2 # 0.0
#inflation_radius: 0.2 # 0.0
#cost_scaling_factor: 50.0


obstacle_layer:
  enabled: true
  max_obstacle_height:  1.0
  unknown_threshold:    15
  mark_threshold:       0
  combination_method:   1
  track_unknown_space:  false    #true needed for disabling global path planning through unknown space

  obstacle_range: 1.0 # 2.0
  raytrace_range: 2.0 # 3.0

  publish_voxel_map: false

  observation_sources: scan
  scan:
    data_type: LaserScan
    topic: scan
    marking: true
    clearing: true
    min_obstacle_height: 0.0
    max_obstacle_height: 1.0
  # for debugging only, let's you see the entire voxel grid




#cost_scaling_factor and inflation_radius were now moved to the inflation_layer ns
inflation_layer:
  enabled:              true
  cost_scaling_factor:  50.0  # exponential rate at which the obstacle cost drops off (default: 10)

static_layer:
  enabled:              true
  