local_costmap:
   global_frame: odom_combined
   robot_base_frame: base_link
   update_frequency: 2.0
   publish_frequency: 1.0
   inflation_radius: 0.2
   robot_radius: 0.15
   width: 2.0
   height: 2.0
   origin_x: 0.0
   origin_y: 0.0
   resolution: 0.05
   static_map: false
   rolling_window: true
   transform_tolerance: 0.5
   plugins:
    - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}


